Web/Controllers/AdminController.cs
using LogicaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class AdminController : Controller
    {
        private Sistema _sistema = Sistema.Instancia;
        public IActionResult Index()
        {
            Usuario adminLogueado = _sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
            string tipo = HttpContext.Session.GetString("tipo");
            
            if (adminLogueado != null && tipo.Trim().ToUpper() == "ADMIN")
            {
                return View();
            } 
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        public IActionResult ListarUsuarios()
        {
            Usuario adminLogueado = _sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
            string tipo = HttpContext.Session.GetString("tipo");
            if (adminLogueado != null && tipo.Trim().ToUpper() == "ADMIN")
            {
                List<Miembro> lista = _sistema.ObtenerListaDeMiembrosOrdenadosPorApellido();
                if (lista.Count > 0)
                {
                    ViewBag.ListaDeMiembros = lista;
                }
                else
                {
                    ViewBag.ListaDeMiembros = "No hay miembros que mostrar";
                }
                return View(); 
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        public IActionResult BloquearMiembros()
        {
            Usuario adminLogueado = _sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
            string tipo = HttpContext.Session.GetString("tipo");
            if (adminLogueado != null && tipo.Trim().ToUpper() == "ADMIN")
            {
                List<Miembro> lista = _sistema.ObtenerMiembrosNoBloqueados();
                if (lista.Count > 0)
                {
                    ViewBag.ListaDeMiembrosNoBloqueados = lista;
                }
                else
                {
                    ViewBag.ListaDeMiembrosNoBloqueados = "No hay miembros disponibles para bloquear";
                }
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }

        }

        [HttpPost]
        public IActionResult BloquearMiembros(string email) {
            Usuario adminLogueado = _sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
            string tipo = HttpContext.Session.GetString("tipo");

            if(adminLogueado != null && tipo.Trim().ToUpper() == "ADMIN"){ 
                Miembro usuarioBuscado = null;
                usuarioBuscado = (Miembro)_sistema.BuscarUsuario(email);

                if (usuarioBuscado!=null)
                {
                    try
                    {
                        _sistema.BloquearUsuario(usuarioBuscado);
                        ViewBag.Msj = "Usuario bloqueado correctamente";
                    }
                    catch(Exception ex)
                    {
                        ViewBag.Msj = ex.Message;
                    }
                }
                else
                {
                    ViewBag.Msj = "No se encontró al usuario en el sistema";
                }

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }


        }

        public IActionResult BanearPost()
        {
            Usuario adminLogueado = _sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
            string tipo = HttpContext.Session.GetString("tipo");

            if (adminLogueado != null && tipo.Trim().ToUpper() == "ADMIN")
            {
                List<Post> lista = _sistema.ObtenerListaDePosts();
                ViewBag.ListaDePost = lista;

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

        [HttpPost]
        public IActionResult BanearPost(int idPost)
        {

            Usuario adminLogueado = _sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
            string tipo = HttpContext.Session.GetString("tipo");

            if (adminLogueado != null && tipo.Trim().ToUpper() == "ADMIN")
            {
                Post post = (Post)_sistema.BuscarPost(idPost);
                if (post != null)
                {
                    if (!post.Censurado)
                    {
                        try
                        {
                            _sistema.BanearPost(post);
                            ViewBag.Msj = "Post baneado con éxito";
                            return View();
                        }
                        catch (Exception ex)
                        {
                            ViewBag.Msj = "Eror al banear el post";
                        }
                    }
                    else
                    {
                        ViewBag.Msj = "El post ya está censurado";
                    }
                }
                else
                {
                    ViewBag.Msj = "No se pudo obtener el post";
                }
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
        }

    }
}

Web/Controllers/MiembroController.cs
using LogicaNegocio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class MiembroController : Controller
    {
        private Sistema _sistema = Sistema.Instancia;
        public IActionResult Index()
        {
            //obtiene datos de Miembro logueado utilizando el email
            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
                Miembro miembroActual = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
                if (miembroActual != null)
                {
                    ViewBag.Usuario = miembroActual.Nombre;
                    List<Post> publicaciones = _sistema.DevolverPostDeUsuarioYamigos(miembroActual.Email);
                    ViewBag.ListarPublicaciones = publicaciones;
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Index(string comentario, string titulo, int id, string accion)
        {
            // REPETIR CODIGO para no crear otra vista comentario y repetir exactamente el Index y el indexhtml para mostrar nuevamente las publicaciones
            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
               Miembro miembroLogueado = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));

               if(miembroLogueado != null)
               {
                    ViewBag.Usuario = miembroLogueado.Nombre;
                    List<Post> publicaciones = _sistema.DevolverPostDeUsuarioYamigos(miembroLogueado.Email);
                    ViewBag.ListarPublicaciones = publicaciones;
                    Publicacion post = _sistema.BuscarPost(id);

                    if (accion.Trim().ToLower() == "enviar"){
                       try
                       {
                            _sistema.NuevoComentario(comentario, miembroLogueado, titulo, (Post)post);
                            ViewBag.Mensaje = "Comentario Agregado";
                       }
                       catch (Exception e)
                       {
                            ViewBag.Mensaje = e.Message;
                       }
                    } 
                    else if (accion.Trim().ToLower() == "like")
                    {
                        try
                        {
                            _sistema.AgregarLike(post.Id, miembroLogueado.Email);
                        } 
                        catch (Exception e)
                        {
                            ViewBag.Mensaje = e.Message;
                        }
                
                    } 
                    else if (accion.Trim().ToLower() == "dislike")
                    {
                        try
                        {
                            _sistema.AgregarDislike(post.Id, miembroLogueado.Email);
                        }
                        catch(Exception e){
                            ViewBag.Mensaje = e.Message;
                        }
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se pudo realizar la acción solicitada";
                    }
               }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }

            return View();
        }


        public IActionResult EnviarSolicitud()
        {
           
            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
                Miembro miembroLogueado = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
                if (miembroLogueado != null)
                {
                    //obtiene lista de Miembros que no son amigos del usuario logueado ni tienen solicitudes pendientes
                    ViewBag.ListaNoAmigos = _sistema.DevolverMiembrosNoAmigos(miembroLogueado.Email);
                }
                else
                {
                    ViewBag.Msj = "No se pudo obtener el usuario logueado";
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
            return View();
        }


        [HttpPost]
        public IActionResult EnviarSolicitud(string email)
        {
            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
                Miembro miembroLogueado = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
                Miembro miembroAEnviarSolicitud = (Miembro)_sistema.BuscarUsuario(email: email);
                if(miembroAEnviarSolicitud != null && miembroLogueado != null){
                    try
                    {
                        _sistema.EnviarSolicitud(miembroLogueado, miembroAEnviarSolicitud);
                        ViewBag.Msj = "Solicitud de amistad enviada con éxito";
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Msj = ex.Message;
                    }
                }
                else { 
                    ViewBag.Msj = "Error, no se pudo obtener a los usuarios para procesar la solicitud";
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }

            return View();
        }

        public IActionResult AceptarRechazarSolicitudes()
        {

            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
                Miembro miembroLogueado = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
                if (miembroLogueado != null)
                {
                    ViewBag.ListaSolicitudes = _sistema.RetornarSolicitudesPendientes(miembroLogueado.Email);
                }
                else
                {
                    ViewBag.Msj = "No se pudo obtener el usuario logueado";
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
            return View();
        }
        
        [HttpPost]
        public IActionResult AceptarRechazarSolicitudes(int id, string accion)
        {
            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
                Miembro miembroLogueado = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
                if (miembroLogueado != null)
                {
                    Solicitud solicitud = _sistema.BuscarSolicitud(id);
                    if (solicitud!=null)
                    {
                        if (accion.Trim().ToLower() == "aceptar")
                        {
                            _sistema.AceptarSolicitud(solicitud);
                            ViewBag.Mensaje = "Solicitud Aceptada";
                        }
                        else
                        {
                            _sistema.RechazarSolicitud(solicitud);
                            ViewBag.Mensaje = "Solicitud Rechazada";
                        }
                    }
                    else
                    {
                        ViewBag.Mensaje = "No existe la solicitud";
                    }
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo obtener el usuario logueado";
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
            return View();
        }

        public IActionResult RealizarPublicacion()
        {

            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
                Miembro miembroLogueado = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
                if (miembroLogueado != null)
                {
                    if (miembroLogueado.Bloqueado)
                    {
                        ViewBag.Mensaje = "No puedes realizar post, estas bloqueado";
                    }
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo obtener el usuario logueado";
                }
            }
            else
            {
                return RedirectToAction("Login", "Usuario");
            }
            return View();
        }

        [HttpPost]
        public IActionResult RealizarPublicacion(string titulo, string contenido, string privacidad, string imagen)
        {
            if (HttpContext.Session.GetString("email") != null && HttpContext.Session.GetString("tipo") == "MIEMBRO")
            {
                Miembro miembroLogueado = (Miembro)_sistema.BuscarUsuario(email: HttpContext.Session.GetString("email"));
                if (miembroLogueado != null)
                {
                    bool publico = false;
                    if (privacidad.Trim().ToLower()=="publico")
                    {
                        publico = true;
                    }
                    try
                    {
                        _sistema.NuevoPost(contenido, miembroLogueado, titulo, publico, imagen);
                        ViewBag.Mensaje = "Se ha publicado con éxito";
                    }
                    catch(Exception e)
                    {
                        ViewBag.Mensaje = e.Message;
                    }
                }
                else

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("tipo") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Inicio de sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Registro">Registrarse</a>
                            </li>
                        }
                        @if (Context.Session.GetString("tipo") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }
                        @if (Context.Session.GetString("tipo") != null && Context.Session.GetString("tipo") == "ADMIN")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ListarUsuarios">Listar usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="BloquearMiembros">Bloquear usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="BanearPost">Banear Post</a>
                            </li>
                        }
                        @if (Context.Session.GetString("tipo") != null && Context.Session.GetString("tipo") == "MIEMBRO")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="Index">Publicaciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="EnviarSolicitud">Enviar solicitud de amistad</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="AceptarRechazarSolicitudes">Aceptar o Rechazar solicitudes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="RealizarPublicacion">Realizar Publicacion</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Miembro" asp-action="ListarPostElegidos">Listar Post Elegidos</a>
                            </li>
                        }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>